


bs = highleveltarget.buildsystem.BuildSystem();

bs = bs.addTask("higleveltarget.buildsystem.CrossCompiler.fun1");
bs = bs.addTask("higleveltarget.buildsystem.CrossCompiler.fun2");

bs = bs.connectTasks(...
    "higleveltarget.buildsystem.CrossCompiler.fun1",...
    "higleveltarget.buildsystem.CrossCompiler.fun2");

bs = bs.addTask("higleveltarget.buildsystem.CrossCompiler.fun3");
bs = bs.addTask("higleveltarget.buildsystem.CrossCompiler.fun4");

bs = bs.connectTasks(...
    "higleveltarget.buildsystem.CrossCompiler.fun2",...
    "higleveltarget.buildsystem.CrossCompiler.fun3");

bs = bs.connectTasks(...
    "higleveltarget.buildsystem.CrossCompiler.fun2",...
    "higleveltarget.buildsystem.CrossCompiler.fun4");

bs = bs.addTask("higleveltarget.buildsystem.CrossCompiler.fun5");

bs = bs.connectTasks(...
    "higleveltarget.buildsystem.CrossCompiler.fun3",...
    "higleveltarget.buildsystem.CrossCompiler.fun5");

bs = bs.connectTasks(...
    "higleveltarget.buildsystem.CrossCompiler.fun4",...
    "higleveltarget.buildsystem.CrossCompiler.fun5");
